apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: pooled-queue
  labels:
    app: enmasse
spec:
  displayName: Pooled Queue
  displayOrder: 0
  shortDescription: Creates a queue on a pooled broker.
  longDescription: Creates a queue on a pooled broker shared with other queues.
  addressType: queue
  resources:
    router: 0.01
    broker: 0.01
