apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: sharded-topic
  labels:
    app: enmasse
spec:
  displayName: Sharded Topic
  displayOrder: 0
  shortDescription: Creates a topic on a standalone broker.
  longDescription: Creates a topic on a standalone broker that can be sharded.
  addressType: topic
  resources:
    router: 0.01
    broker: 1.0
