apiVersion: admin.enmasse.io/v1beta2
kind: AddressPlan
metadata:
  name: standard-anycast
  labels:
    app: enmasse
spec:
  displayName: Standard
  displayOrder: 0
  shortDescription: Creates a direct anycast address.
  longDescription: Creates a direct anycast address where messages go via a router that does not take ownership of the messages.
  addressType: anycast
  resources:
    router: 0.01
    broker: 0.0
    
